### ISSUE TITLE
Templates not rendering in preview

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/document-service#22]
Subsequent to deployment of #20 on a Docker instance, I am not seeing any preview after uploading a template. There is a 400 error in the JS console, and the following error logged on the server:

```
RI: /api/admin/template/ide/download/ad7c0904-15a3-471e-81dd-a8442d5de5d5 
xes-platform        | [echo] 2021-12-15T18:24:58+01:00 client=85.195.230.200, method=GET, uri=/api/admin/template/ide/download/ad7c0904-15a3-471e-81dd-a8442d5de5d5, status=400
xes_document_service | com.proxeus.error.UnavailableException: Cannot initialize LibreOffice instance. Please try again later.
xes_document_service |  at com.proxeus.office.libre.LibreOfficeAssistant.Convert(LibreOfficeAssistant.java:73)
xes_document_service |  at com.proxeus.document.odt.ODTRenderer.format(ODTRenderer.java:179)
xes_document_service |  at com.proxeus.document.odt.ODTRenderer.compile(ODTRenderer.java:83)
xes_document_service |  at com.proxeus.document.odt.ODTCompiler.compile(ODTCompiler.java:106)
xes_document_service |  at com.proxeus.document.odt.ODTCompiler.Compile(ODTCompiler.java:80)
xes_document_service |  at com.proxeus.document.TemplateCompiler.compile(TemplateCompiler.java:37)
xes_document_service |  at com.proxeus.SparkServer.lambda$new$4(SparkServer.java:126)
xes_document_service |  at spark.RouteImpl$1.handle(RouteImpl.java:72)
xes_document_service |  at spark.http.matching.Routes.execute(Routes.java:61)
xes_document_service |  at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
xes_document_service |  at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
xes_document_service |  at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1584)
xes_document_service |  at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
xes_document_service |  at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
xes_document_service |  at org.eclipse.jetty.server.Server.handle(Server.java:501)
xes_document_service |  at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
xes_document_service |  at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
xes_document_service |  at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
xes_document_service |  at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:273)
xes_document_service |  at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
xes_document_service |  at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
xes_document_service |  at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
xes_document_service |  at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
xes_document_service |  at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
xes_document_service |  at java.lang.Thread.run(Thread.java:748)
```

**Comment by loleg** [comment]
Template previews are working again.
