### ISSUE TITLE
Upgrading to a newer Java release

### ISSUE THREAD

**Issue by loleg** [ProxeusApp/document-service#23]
Currently there are issues related to [SocksSocketImpl](https://stackoverflow.com/questions/19735305/why-is-java-net-sockssocketimpl-the-default-java-net-socket-implementation-in-ja#19735717) when starting the application on a modern Java release:

```
Exception in thread "Thread-1" Exception in thread "Thread-0" java.lang.NoClassDefFoundError: Could not initialize class java.net.SocksSocketImpl
	at java.base/java.net.ServerSocket.setImpl(ServerSocket.java:308)
	at java.base/java.net.ServerSocket.<init>(ServerSocket.java:108)
	at com.proxeus.office.libre.conn.BootstrapSocketConnector.connect(BootstrapSocketConnector.java:39)
	at com.proxeus.office.libre.exe.LibreOffice.reconnect(LibreOffice.java:73)
	at com.proxeus.office.libre.exe.LibreOffice.<init>(LibreOffice.java:52)
	at com.proxeus.office.libre.exe.LibreOfficePool.tryNewLibreOffice(LibreOfficePool.java:340)
	at com.proxeus.office.libre.exe.LibreOfficePool.prepare(LibreOfficePool.java:243)
	at com.proxeus.office.libre.exe.LibreOfficePool.access$000(LibreOfficePool.java:35)
	at com.proxeus.office.libre.exe.LibreOfficePool$2.run(LibreOfficePool.java:132)
```

Which may also be related to the Jetty server .. and warnings like:

`Illegal reflective access by com.proxeus.office.libre.exe.LibreOfficePool (file:/.../document-service.jar) to field java.lang.ClassLoader.sys_paths`

**Comment by loleg** [comment]
After further analysis, I find that the initial warnings were due to mismatched LibreOffice versions, which need to be locked for these operations to succeed.

The second warning has to do with the newer version of Java, and is explained [well here](https://github.com/spring-projects/spring-framework/issues/22674#issuecomment-589116539) in context of Spring Framework.

**Comment by loleg** [comment]
One of the reflective access warnings is coming from a third-party dependency, [parboiled via jtwig](https://github.com/sirthias/parboiled/issues/128). It should possible to ignore it using this command:

`--add-opens=java.base/java.lang=ALL-UNNAMED`

However, from JDK 17 this will result in an unrecoverable exception.

**Comment by loleg** [comment]
Upgrade to JDK 11 seems to be successful, and I am closing this issue for now.
